[package]
name = "coppice-names-sqlite"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "Apache-2.0"
repository = "https://github.com/nfl0/coppice-names"
publish = false

[features]
default = []
wallet-extension = ["dep:zcash_client_sqlite"]

[lints]
workspace = true

[dependencies]
coppice.workspace = true
coppice-names.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
zcash_client_sqlite = { workspace = true, optional = true }

[dev-dependencies]
tempfile = "3"
