[package]
name = "coppice-names"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "Apache-2.0"
repository = "https://github.com/nfl0/coppice-names"
publish = false

[lints]
workspace = true

[dependencies]
blake2b_simd = "1"
coppice.workspace = true
halo2_gadgets = { workspace = true }
halo2_proofs = { workspace = true }
hex = "0.4"
orchard = { workspace = true, features = ["std", "state-note"] }
pasta_curves = { workspace = true }
rand_core = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
postcard.workspace = true
sha2 = "0.10"
zcash_address.workspace = true

[dev-dependencies]
zcash_protocol.workspace = true
