[package]
name = "coppice-names-librustzcash"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
coppice-names.workspace = true
coppice.workspace = true
coppice-librustzcash.workspace = true
orchard.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
sapling.workspace = true
incrementalmerkletree.workspace = true
shardtree.workspace = true
zcash_client_backend = { workspace = true, features = ["orchard"] }
zcash_address.workspace = true
zcash_keys = { workspace = true, features = ["orchard", "sapling", "std"] }
zcash_primitives.workspace = true
zcash_protocol.workspace = true
zip321.workspace = true

[dev-dependencies]
hex.workspace = true
rand_chacha.workspace = true
serde_json.workspace = true
zcash_note_encryption.workspace = true
zip32.workspace = true
